### ISSUE TITLE
Change button size

### ISSUE THREAD

**Issue by Vistaus** [yagomont/material-decoration-bt#2]
Other window decorations allow me to change the button size, but not this one. It would be nice if I could change it as the buttons are way too big on my screen.

**Comment by yagomont** [comment]
You can edit the title bar height in sec/Decoration.cc

Then build the decoration again.

**Comment by yagomont** [comment]
![Screenshot_20190717-083436_Chrome Dev](https://user-images.githubusercontent.com/14876659/61372585-f6fa2100-a86d-11e9-935c-66edcb32fc4c.jpg)
Just edit the value 1.3 to something smaller. Any size is possible with this change and it adjusts the buttons aswell.

I might add this functionality to bt-opacity in the future. Maybe.

**Comment by Vistaus** [comment]
> You can edit the title bar height in sec/Decoration.cc
> 
> Then build the decoration again.

So instead of doing it the KDE way (why else would they have added that feature and why else would other themes use it?) where I can instantly see the change, I have to edit a file, hope I used the correct height that I'm after and re-compile and re-apply the whole thing. I'm not against editing files, but in this case, it's very cumbersome (and this is the first theme I have ever encountered where I should do it this way instead of the KDE way).

Edit: and it doesn't even work. So not only is it cumbersome, but the solution doesn't even change a thing.

**Comment by yagomont** [comment]
If you want to take it in your hands and implement it the KDE way, go ahead.

I'm not a programmer by any means. I just like Linux. Perhaps ask the developer of this decoration?

**Comment by Vistaus** [comment]
But still, changing that file didn't work, so even the non-KDE way doesn't work. That's a shame.

**Comment by yagomont** [comment]
Odd. Let me have a look
